theme: jekyll-theme-minimal

# Name of website
title: Victor Ruela

description: "Hello! This website showcases my main projects and interests, hope you like it :) \n Contact me at: victorspruela@gmail.com"

logo: profile_pic.jpg

